//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSASAcademico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademicoContainer : DbContext
    {
        public AcademicoContainer()
            : base("name=AcademicoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListaExercicios> Atividade { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<Exercicio> Exercicio { get; set; }
    }
}
