//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSASAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio
    {
        public int IdExercicio { get; set; }
        public string enunciado { get; set; }
        public string respostaAluno { get; set; }
        public string respostaProfessor { get; set; }
        public string comentario { get; set; }
        public int IdListaExercicios { get; set; }
        public string identificador { get; set; }
    
        public virtual ListaExercicios ListaExercicios { get; set; }
    }
}
