//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSASAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public int IdTurma { get; set; }
        public string descricao { get; set; }
        public int condicaoLimiteUm { get; set; }
        public Nullable<int> condicaoLimiteDois { get; set; }
    }
}
